import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RecoilContextProviderNoSSr = dynamic(
    () => import("@/app/store/RecoilContextProvider"),
    { ssr: false }
);

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <RecoilContextProviderNoSSr>
                    {children}
                </RecoilContextProviderNoSSr>
            </body>
        </html>
    );
}
